#!/bin/bash
password=$1
parent_path=$( cd "$(dirname "${BASH_SOURCE[0]}")" ; pwd -P )
pushd "$parent_path"


PGPASSWORD="$password" psql -d food -U usda < abbreviated.sql
PGPASSWORD="$password" psql -d food -U usda < data_sources_link.sql
PGPASSWORD="$password" psql -d food -U usda < data_sources.sql
PGPASSWORD="$password" psql -d food -U usda < dd_code_desc.sql
PGPASSWORD="$password" psql -d food -U usda < food_description.sql
PGPASSWORD="$password" psql -d food -U usda < food_group_description.sql
PGPASSWORD="$password" psql -d food -U usda < footnotes.sql
PGPASSWORD="$password" psql -d food -U usda < langual_factor_description.sql
PGPASSWORD="$password" psql -d food -U usda < langual_factor.sql
PGPASSWORD="$password" psql -d food -U usda < nutrient_data.sql
PGPASSWORD="$password" psql -d food -U usda < nutrient_definition.sql
PGPASSWORD="$password" psql -d food -U usda < source_code.sql
PGPASSWORD="$password" psql -d food -U usda < weight.sql

popd